import type { RenderedBrief } from "./domain.js";
import { recordInstructions } from "./record-usage.js";
import { skillMethod } from "./skills.js";

// What a worker records when it finishes.
export const WORKER_REPORT = recordInstructions(
  ["handoff"],
  [
    "- `done` when the unit's goal is met and you have shown it; `stuck` when you cannot go on (say what stops you with --reason). Running it again replaces your handoff, so repeat everything you recorded before.",
    "- --did once per line of what you did. --evidence: what proves it, as run ids (`run:42`, from `yagura evidence run`), commits, and file:line. --decision: each choice the brief did not settle, what you deliberately did not do, and why. --note: assumptions and surprises. --follow-up: tasks worth doing next.",
  ],
);

export class UnfillableBrief extends Error {
  constructor(readonly missing: string[]) {
    super(`brief cannot be spawned; missing: ${missing.join(", ")}`);
  }
}

export function missingBriefFields(brief: Pick<RenderedBrief, "goal" | "acceptance">): string[] {
  const missing: string[] = [];
  if (!brief.goal.trim()) missing.push("GOAL");
  if (brief.acceptance.length === 0) missing.push("ACCEPTANCE");
  return missing;
}

const list = (items: string[], empty = "(none)") => (items.length ? items.map((i) => `- ${i}`).join("\n") : empty);

export function renderBrief(b: RenderedBrief): string {
  const missing = missingBriefFields(b);
  if (missing.length) throw new UnfillableBrief(missing);
  const env = Object.entries(b.env).map(([k, v]) => `${k}=${v}${b.envNotes?.[k] ? ` (${b.envNotes[k]})` : ""}`);
  return `# yagura brief

You are running inside yagura. You cannot ask questions: everything you need is below. Work only in your checkout, commit to your branch, and prove the work with recorded runs. Then record your handoff as REPORT says.

## GOAL
${b.goal}

## REPO
- repo: ${b.repo.id}
- checkout: ${b.repo.worktree} (your working directory)
- branch: ${b.repo.branch}, which started at ${b.repo.baseSha}
- commit your work to this branch; you may push it (\`git push\`) whenever you like, never another branch, and never with force
- a judge with no part in your work decides whether the goal is met, from your change and from runs it makes itself

## CONTEXT
${list(b.context)}

## READONLY
${list(b.readonly.map((r) => `${r.repoId} at ${r.path} @ ${r.sha}${r.version ? `, published as ${r.version}: pin exactly this version wherever this repo depends on ${r.repoId}` : ""}`))}

## ACCEPTANCE
${list(b.acceptance)}

## TESTS
${b.test ?? "yagura was not told how this environment runs the repo's tests: work out the command, use it, and say so in your decision log."}
Commit, then run the command that proves your point with \`yagura evidence run -- <command>\`: yagura runs it itself on your commit and gives you a run id to cite.

## ENV
${list(env)}

## TIMEBOX
${b.timeboxMinutes} minutes. If you cannot finish, commit what you have and hand off stuck with the reason.

## FORBIDDEN
${list(b.forbidden)}

## METHOD
${b.method}

## REPORT
${b.report}

## STANDING ORDERS
${b.standing.trim() || "(none)"}
`;
}

export interface PlanBrief {
  project: { id: string; goal: string; predicate: string };
  repos: { id: string; path: string; trunkSha: string }[];
  status: string;
  playbooks: readonly string[];
  standing: string;
  timeboxMinutes: number;
  spec?: string | null;
  scaffoldSkills?: string[];
  references?: string[];
}

export function renderPlanBrief(p: PlanBrief): string {
  return `# yagura plan brief

You are the planner for project ${p.project.id}. You never write code. You read the project's state and the code, then return a plan delta: the next units of work for other agents. yagura validates your delta and applies all of it or none of it.

## GOAL
${p.project.goal}

## DONE WHEN
${p.project.predicate}

## CODE (read-only checkouts at trunk)
${list(p.repos.map((r) => `${r.id}: ${r.path} @ ${r.trunkSha}`))}
${p.spec ? `\n## SPEC\nThe developer's living spec for this project, kept current by the watchman and the developer. Read it before planning; it outranks older assumptions.\n\n${p.spec.trim()}\n` : ""}
## CURRENT STATE (generated by yagura from its records)
${p.status}

## HOW TO PLAN
- Only plan what the state calls for. Do not re-add work that is building, judging, ready, merged, or queued.
- Each unit is one worker session in one repo and ends as one pull request: small enough for about ${Math.round(p.timeboxMinutes)} minutes of focused work, complete enough to judge on its own. A unit says what must be true when it is done, never which files to touch.
- \`goal\` is one sentence. \`acceptance\` lines are outcomes a judge can check by running code ("\`greet('Jimmy')\` returns \`Hello, Jimmy\`"), one behaviour each.
- \`context\` is what the worker should know: why the unit exists now, decisions already made, pointers into the spec, and what other units will build, so a deliberate gap is not mistaken for a placeholder.
- \`after\` names units that must merge first: a key from this delta or an existing unit such as "U3". Before you record the plan, check that the units fit together: what one unit's acceptance needs is what another produces (a library change and the app that uses it agree on what the function returns).
- \`base\` (optional) is the branch the unit starts from and merges into; leave it out for the repo's default branch.
- \`playbook\` is one of: ${p.playbooks.join(", ")}.
- \`scaffold\`: true marks the unit that builds a new project's skeleton. ${p.scaffoldSkills?.length ? `This project names scaffold skills (${p.scaffoldSkills.join(", ")}): when a repo has no project skeleton yet, make its first unit a scaffold unit and let later units build on it.` : "This project names no scaffold skills; leave it false."}${p.references?.length ? `\n- Workers get read-only checkouts of reference repos that already do it right (${p.references.join(", ")}); point at them in \`context\` when a unit should follow their shape.` : ""}
- \`disagreement\` (optional): when a unit fixes forward something the developer disagreed with (listed under "The developer disagrees" with a D number), set it to that number, e.g. 4 for D4. Every open disagreement needs such a unit, or a planner gate that asks the developer how to proceed.
- \`refs\` (optional) lists issue keys the unit addresses, e.g. "gitlab#123"; the project's own refs are added automatically.
- A stuck unit can be retried with a note that changes what the next attempt does, split into new units, or cancelled.
- A unit that has not started can be amended in place, including its \`after\` (the list replaces its old one). To move units off a stuck one, amend their \`after\`; do not cancel and re-add them.
- Ask the human only for a product or preference decision no experiment can settle, with a default.
- Set "done": true only when the DONE WHEN condition is met by merged work.

## METHOD
Load the yagura-planner skill first and follow it.

## REPORT
${recordInstructions(
  ["plan"],
  [
    "- Write the delta to a file in your scratch directory and record it with `yagura plan --file <path>`. yagura checks it the way applying it would (schema, repos, dependencies) and says at once what to fix; run it again with the corrected file. The delta has this shape:",
  ],
)}

\`\`\`json
{
  "add": [
    {
      "key": "discount-on-create",
      "repo": "${p.repos[0]?.id ?? "repo-id"}",
      "goal": "one sentence a stranger could execute",
      "acceptance": ["checkable outcome", "another"],
      "context": ["why this comes now, decisions already made, files or docs to read first"],
      "playbook": "feature",
      "after": ["U1"]
    }
  ],
  "amend": [{ "unit": "U4", "after": ["discount-on-create"] }],
  "retry": [{ "unit": "U2", "note": "what the next attempt must do differently" }],
  "cancel": [{ "unit": "U5", "reason": "why it is no longer needed" }],
  "gates": [],
  "done": false,
  "summary": "what this plan does and why"
}
\`\`\`

## STANDING ORDERS
${p.standing.trim() || "(none)"}
`;
}
